In [85]:
import pandas as pd

In [86]:
t = pd.read_csv("C:/Users/PARTHIV/Downloads\Hierarchy and Field Options.xlsx - New Hierarchy (4).csv")
h = pd.read_csv("../static/hierarchy.csv")

t.standard_size = t.standard_size.astype("str")
t = t.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
t = t.apply(lambda x: x.str.title() if x.name in {
    "gender",
    "vertical",
    "fabric_category",
    "brand",
    "usage",
    "brick",
    "product",
    "sub_product",
    "target_audience",
    "fit",
} else x)

# t.sub_product.replace("Kaftaan", "Kaftan", inplace=True)
# t.fit.replace("Flared", "Flare", inplace=True)
# t.usage.replace("Causal", "Casual", inplace=True)

t.drop_duplicates(inplace=True)

In [87]:
t.gender.unique(), t.vertical.unique(), t.fabric_category.unique(), t.brand.unique(), t.brick.unique(),  t.target_audience.unique()

(array(['Men'], dtype=object),
 array(['Apparel'], dtype=object),
 array(['Woven', 'Knitted'], dtype=object),
 array(['The Indian Garage Co'], dtype=object),
 array(['Bottomwear', 'Topwear', 'Coordinates'], dtype=object),
 array(['Core', 'Youth'], dtype=object))

In [88]:
sorted(t.usage.unique())

['Casual', 'Resort', 'Smart Casual', 'Street']

In [89]:
sorted(t.sub_product.unique())

['Bomber Jacket',
 'Cargo',
 'Crew Neck T-Shirt And Shorts',
 'Gurkha Pants',
 'Hooded Shirt',
 'Overshirt',
 'V-Neck T-Shirt']

In [90]:
sorted(t.fit.unique())

['Baggy',
 'Boxy',
 'Loose Tapered',
 'Relaxed',
 'Relaxed Cargo',
 'Relaxed Straight',
 'Slim']

In [91]:
sorted(t.standard_size.unique())

['28', '30', '32', '34', '36', 'L', 'M', 'S', 'XL', 'XXL']

In [92]:
h.set_index(['gender', 'vertical', 'fabric_category', 'brand', 'usage', 'brick',
       'product', 'sub_product', 'target_audience', 'fit', 'standard_size'], inplace=True)
t.set_index(['gender', 'vertical', 'fabric_category', 'brand', 'usage', 'brick',
       'product', 'sub_product', 'target_audience', 'fit', 'standard_size'], inplace=True)
common_index = h.index.intersection(t.index)

In [93]:
h.loc[common_index]

                                                                                                                               barcode_size  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                 28/71cm
                                                                                                                 30                 30/76cm
                                                                                                                 32                 32/81cm
                                                                                                                 34                 34/86cm
                                                                                                                 36                 36/91cm

                                                                                                                                garment_waist  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                      26.0
                                                                                                                 30                      28.0
                                                                                                                 32                      30.0
                                                                                                                 34                      32.0
                                                                                                                 36                      34.0

                                                                                                                                inseam_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                      27.0
                                                                                                                 30                      27.0
                                                                                                                 32                      27.0
                                                                                                                 34                      27.0
                                                                                                                 36                      27.0

                                                                                                                                to_fit_waist  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                     28.0
                                                                                                                 30                     30.0
                                                                                                                 32                     32.0
                                                                                                                 34                     34.0
                                                                                                                 36                     36.0

                                                                                                                                across_shoulder  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                         NaN
                                                                                                                 30                         NaN
                                                                                                                 32                         NaN
                                                                                                                 34                         NaN
                                                                                                                 36                         NaN

                                                                                                                                chest  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28               NaN
                                                                                                                 30               NaN
                                                                                                                 32               NaN
                                                                                                                 34               NaN
                                                                                                                 36               NaN

                                                                                                                                front_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                      NaN
                                                                                                                 30                      NaN
                                                                                                                 32                      NaN
                                                                                                                 34                      NaN
                                                                                                                 36                      NaN

                                                                                                                                to_fit_foot_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                            NaN
                                                                                                                 30                            NaN
                                                                                                                 32                            NaN
                                                                                                                 34                            NaN
                                                                                                                 36                            NaN

                                                                                                                                outseam length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                        NaN
                                                                                                                 30                        NaN
                                                                                                                 32                        NaN
                                                                                                                 34                        NaN
                                                                                                                 36                        NaN

                                                                                                                                sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                       NaN
                                                                                                                 30                       NaN
                                                                                                                 32                       NaN
                                                                                                                 34                       NaN
                                                                                                                 36                       NaN

                                                                                                                                outseam_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                      39.00
                                                                                                                 30                      39.25
                                                                                                                 32                      39.50
                                                                                                                 34                      39.75
                                                                                                                 36                      40.00

                                                                                                                                Sleeve length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                       NaN
                                                                                                                 30                       NaN
                                                                                                                 32                       NaN
                                                                                                                 34                       NaN
                                                                                                                 36                       NaN

                                                                                                                                full_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                            NaN
                                                                                                                 30                            NaN
                                                                                                                 32                            NaN
                                                                                                                 34                            NaN
                                                                                                                 36                            NaN

                                                                                                                                half_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                            NaN
                                                                                                                 30                            NaN
                                                                                                                 32                            NaN
                                                                                                                 34                            NaN
                                                                                                                 36                            NaN

                                                                                                                                long_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                            NaN
                                                                                                                 30                            NaN
                                                                                                                 32                            NaN
                                                                                                                 34                            NaN
                                                                                                                 36                            NaN

                                                                                                                                short_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                             NaN
                                                                                                                 30                             NaN
                                                                                                                 32                             NaN
                                                                                                                 34                             NaN
                                                                                                                 36                             NaN

                                                                                                                                quarter_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                               NaN
                                                                                                                 30                               NaN
                                                                                                                 32                               NaN
                                                                                                                 34                               NaN
                                                                                                                 36                               NaN

                                                                                                                                to__waist  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                   NaN
                                                                                                                 30                   NaN
                                                                                                                 32                   NaN
                                                                                                                 34                   NaN
                                                                                                                 36                   NaN

                                                                                                                                to__foot_length
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                         NaN
                                                                                                                 30                         NaN
                                                                                                                 32                         NaN
                                                                                                                 34                         NaN
                                                                                                                 36                         NaN

In [94]:
t.loc[common_index]

                                                                                                                               barcode_size  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                 28/71cm
                                                                                                                 30                 30/76cm
                                                                                                                 32                 32/81cm
                                                                                                                 34                 34/86cm
                                                                                                                 36                 36/91cm

                                                                                                                                garment_waist  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                      26.0
                                                                                                                 30                      28.0
                                                                                                                 32                      30.0
                                                                                                                 34                      32.0
                                                                                                                 36                      34.0

                                                                                                                                inseam_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                      27.0
                                                                                                                 30                      27.0
                                                                                                                 32                      27.0
                                                                                                                 34                      27.0
                                                                                                                 36                      27.0

                                                                                                                                to_fit_waist  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                     28.0
                                                                                                                 30                     30.0
                                                                                                                 32                     32.0
                                                                                                                 34                     34.0
                                                                                                                 36                     36.0

                                                                                                                                outseam_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                      39.00
                                                                                                                 30                      39.25
                                                                                                                 32                      39.50
                                                                                                                 34                      39.75
                                                                                                                 36                      40.00

                                                                                                                                across_shoulder  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                         NaN
                                                                                                                 30                         NaN
                                                                                                                 32                         NaN
                                                                                                                 34                         NaN
                                                                                                                 36                         NaN

                                                                                                                                chest  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28               NaN
                                                                                                                 30               NaN
                                                                                                                 32               NaN
                                                                                                                 34               NaN
                                                                                                                 36               NaN

                                                                                                                                front_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                      NaN
                                                                                                                 30                      NaN
                                                                                                                 32                      NaN
                                                                                                                 34                      NaN
                                                                                                                 36                      NaN

                                                                                                                                full_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                            NaN
                                                                                                                 30                            NaN
                                                                                                                 32                            NaN
                                                                                                                 34                            NaN
                                                                                                                 36                            NaN

                                                                                                                                half_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                            NaN
                                                                                                                 30                            NaN
                                                                                                                 32                            NaN
                                                                                                                 34                            NaN
                                                                                                                 36                            NaN

                                                                                                                                long_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                            NaN
                                                                                                                 30                            NaN
                                                                                                                 32                            NaN
                                                                                                                 34                            NaN
                                                                                                                 36                            NaN

                                                                                                                                short_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                             NaN
                                                                                                                 30                             NaN
                                                                                                                 32                             NaN
                                                                                                                 34                             NaN
                                                                                                                 36                             NaN

                                                                                                                                quarter_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                               NaN
                                                                                                                 30                               NaN
                                                                                                                 32                               NaN
                                                                                                                 34                               NaN
                                                                                                                 36                               NaN

                                                                                                                                to_fit_foot_length
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                            NaN
                                                                                                                 30                            NaN
                                                                                                                 32                            NaN
                                                                                                                 34                            NaN
                                                                                                                 36                            NaN

In [95]:
h[h.index.duplicated(keep=False)]

Empty DataFrame
Columns: [barcode_size, garment_waist, inseam_length, to_fit_waist, across_shoulder, chest, front_length, to_fit_foot_length, outseam length, sleeve_length, outseam_length, Sleeve length, full_sleeve_length, half_sleeve_length, long_sleeve_length, short_sleeve_length, quarter_sleeve_length, to__waist, to__foot_length]
Index: []

In [96]:
t[t.index.duplicated(keep=False)]

Empty DataFrame
Columns: [barcode_size, garment_waist, inseam_length, to_fit_waist, outseam_length, across_shoulder, chest, front_length, full_sleeve_length, half_sleeve_length, long_sleeve_length, short_sleeve_length, quarter_sleeve_length, to_fit_foot_length]
Index: []

In [97]:
# t[t.index.duplicated(keep=False)].to_csv('../static/duplicate-hierarchies.csv')
# t = t[~t.index.duplicated(keep='last')]

In [98]:
h.update(t)
h.loc[common_index]

# print(h.index[h.index.duplicated(keep=False)])
# h.loc[common_index, :] = t.loc[common_index, :]

                                                                                                                               barcode_size  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                 28/71cm
                                                                                                                 30                 30/76cm
                                                                                                                 32                 32/81cm
                                                                                                                 34                 34/86cm
                                                                                                                 36                 36/91cm

                                                                                                                                garment_waist  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                      26.0
                                                                                                                 30                      28.0
                                                                                                                 32                      30.0
                                                                                                                 34                      32.0
                                                                                                                 36                      34.0

                                                                                                                                inseam_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                      27.0
                                                                                                                 30                      27.0
                                                                                                                 32                      27.0
                                                                                                                 34                      27.0
                                                                                                                 36                      27.0

                                                                                                                                to_fit_waist  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                     28.0
                                                                                                                 30                     30.0
                                                                                                                 32                     32.0
                                                                                                                 34                     34.0
                                                                                                                 36                     36.0

                                                                                                                                across_shoulder  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                         NaN
                                                                                                                 30                         NaN
                                                                                                                 32                         NaN
                                                                                                                 34                         NaN
                                                                                                                 36                         NaN

                                                                                                                                chest  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28               NaN
                                                                                                                 30               NaN
                                                                                                                 32               NaN
                                                                                                                 34               NaN
                                                                                                                 36               NaN

                                                                                                                                front_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                      NaN
                                                                                                                 30                      NaN
                                                                                                                 32                      NaN
                                                                                                                 34                      NaN
                                                                                                                 36                      NaN

                                                                                                                                to_fit_foot_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                            NaN
                                                                                                                 30                            NaN
                                                                                                                 32                            NaN
                                                                                                                 34                            NaN
                                                                                                                 36                            NaN

                                                                                                                                outseam length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                        NaN
                                                                                                                 30                        NaN
                                                                                                                 32                        NaN
                                                                                                                 34                        NaN
                                                                                                                 36                        NaN

                                                                                                                                sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                       NaN
                                                                                                                 30                       NaN
                                                                                                                 32                       NaN
                                                                                                                 34                       NaN
                                                                                                                 36                       NaN

                                                                                                                                outseam_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                      39.00
                                                                                                                 30                      39.25
                                                                                                                 32                      39.50
                                                                                                                 34                      39.75
                                                                                                                 36                      40.00

                                                                                                                                Sleeve length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                       NaN
                                                                                                                 30                       NaN
                                                                                                                 32                       NaN
                                                                                                                 34                       NaN
                                                                                                                 36                       NaN

                                                                                                                                full_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                            NaN
                                                                                                                 30                            NaN
                                                                                                                 32                            NaN
                                                                                                                 34                            NaN
                                                                                                                 36                            NaN

                                                                                                                                half_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                            NaN
                                                                                                                 30                            NaN
                                                                                                                 32                            NaN
                                                                                                                 34                            NaN
                                                                                                                 36                            NaN

                                                                                                                                long_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                            NaN
                                                                                                                 30                            NaN
                                                                                                                 32                            NaN
                                                                                                                 34                            NaN
                                                                                                                 36                            NaN

                                                                                                                                short_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                             NaN
                                                                                                                 30                             NaN
                                                                                                                 32                             NaN
                                                                                                                 34                             NaN
                                                                                                                 36                             NaN

                                                                                                                                quarter_sleeve_length  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                               NaN
                                                                                                                 30                               NaN
                                                                                                                 32                               NaN
                                                                                                                 34                               NaN
                                                                                                                 36                               NaN

                                                                                                                                to__waist  \
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                   NaN
                                                                                                                 30                   NaN
                                                                                                                 32                   NaN
                                                                                                                 34                   NaN
                                                                                                                 36                   NaN

                                                                                                                                to__foot_length
gender vertical fabric_category brand                usage  brick      product sub_product target_audience fit   standard_size
Men    Apparel  Woven           The Indian Garage Co Street Bottomwear Cargo   Cargo       Core            Baggy 28                         NaN
                                                                                                                 30                         NaN
                                                                                                                 32                         NaN
                                                                                                                 34                         NaN
                                                                                                                 36                         NaN

In [99]:
t.drop(common_index, inplace=True)
h = h.append(t)

C:\Users\PARTHIV\AppData\Local\Temp\ipykernel_1456\2307150090.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  h = h.append(t)

In [100]:
h.reset_index(inplace=True)
h.to_csv('../static/hierarchy.csv', index=False)

In [101]:
# REMINDER: bump the version

In [102]:
# REMINDER: bump the version